### PR TITLE
Improve Footer UI/UX: Better Spacing, Alignment, and Visual Consistency

### LINKED ISSUE #605: Footer Needs UI/UX Improvements for Better Spacing, Alignment, and Visual Consistency
The current footer design has some usability and visual hierarchy issues that can be enhanced to improve the overall user experience and appearance. The spacing, alignment, and color scheme of certain elements like the social media icons, visitor counter, and copyright text could benefit from refinement. Here are the details of the issues and suggested improvements:Issues Identified:

Spacing and Alignment:

The social media icons are closely packed together, making the footer feel cramped.
The visitor counter and social media icons do not seem evenly aligned, and the overall layout feels inconsistent.
There's little padding between the social icons and the copyright text, causing visual clutter.
Visual Hierarchy:

The visitor counter is too prominent for its purpose. It draws too much attention compared to more important elements.
The font size and color contrast for the copyright section could be improved for better readability against the dark background.
Social Media Icons:

The icons lack hover effects, which reduces interactivity and visual feedback for users.
The current color scheme of the icons is inconsistent. Some icons use brand colors, while others don't.
Back-to-Top Button:

The "Back to Top" button’s design could be more aligned with the site’s theme, and it feels disconnected from the rest of the footer in terms of styling.
Suggested Improvements:

Improve Spacing and Alignment:

Increase the space between social media icons and ensure they are evenly distributed.
Add more padding between the icons and the copyright text for better separation.
Center-align the visitor counter and social icons for a more symmetrical layout.

### PR DESCRIPTION
**Pull request by amanver45**
close #605
This PR addresses the issues related to the footer's UI/UX by enhancing its spacing, alignment, and overall visual consistency. The changes ensure that the footer design is more aesthetically pleasing and user-friendly across different screen sizes. Key improvements include:

Improved spacing between footer elements.
Adjusted alignment for better symmetry and balance.
Enhanced visual consistency to match the overall website design. These enhancements aim to provide a cleaner and more cohesive footer layout for a better user experience.

https://github.com/user-attachments/assets/61264df9-759c-4406-979b-693cdcd883b0

### CODE REVIEW

**Comment by amanver45** [comment]
@dohinafs pls check and merge this pr

**Comment by amanver45** [comment]
@dohinafs  pls check and merge this pr

**Comment by amanver45** [comment]
@dohinafs  pls check this pr

**Comment by MastanSayyad** [comment]
@dohinafs Are you active? if yes please merge the open PRs

**Pull request merged**
