### PR TITLE
+ and - buttons added

### PR DESCRIPTION
**Pull request by Jerusha547**
I have added + and - buttons to adjust the no of items to add to the cart at a time.
I have also modified the functionality of displaying cart.

https://github.com/user-attachments/assets/8de95441-37c4-43bc-81ea-eb93a316354a

### CODE REVIEW

**Comment by Jerusha547** [comment]
I have resolved the issue #336 . Now you may review it. Thank you.

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly solve the following issues:
1. The items are added but the price in the checkout doesn't change. Below there are two items in cart, but it reflects only the price of one. 
image

2. The design of the button doesn't suit the card, make it have similar design to the other buttons in the card without solid outlines. 
image

**Comment by Jerusha547** [comment]
@dohinafs, Okay I will make the changes

**Comment by Jerusha547** [comment]
I have made the requested changes

https://github.com/user-attachments/assets/4191afb7-6e2e-4833-999e-5030d6f17a48

**Review by dohinafs — APPROVED** [review]

**Pull request merged**
