### PR TITLE
Enhanced Ice-Cream Cards Animations & Button Functionality!

### LINKED ISSUE #147: Enhance IceCream Menu Cards and All Buttons
Will improve the cards in ice cream menu section and improve the universal UI of the website including animated buttons and themes.

### PR DESCRIPTION
**Pull request by Kevindua26**
## What does this PR do?

This pull request addresses the modifications made to the ice-cream-cards on the website as part of the issue assigned earlier.

## Fixes

- Close #147 

## Type of change

1. **Updated Animations:**

- Improved the animations within the ice-cream-cards to provide a smoother and more visually appealing experience.

- Ensured the animations are responsive and perform well across different devices and screen sizes.

2. **Modified Button Functionality:**

- Refined the button styles and functionality inside the ice-cream-cards for better interactivity and user experience.

- Adjusted the hover effects and transitions to align with the overall design theme of the website. 

## Screen Shots

Screenshot 2024-10-09 130215
Screenshot 2024-10-09 130236

## Message

Hey @dohinafs you can check the PR now, there's no conflicts in merging to the `main` branch, also give me the `enhancement` `hacktoberfest` `hacktoberfest-accepted` `gssoc-ext` `gssoc` and the level.

### CODE REVIEW

**Comment by Kevindua26** [comment]
Hey @dohinafs you can check the PR now, there's no conflicts in merging to the `main` branch, also give me the `enhancement` `hacktoberfest` `hacktoberfest-accepted` `gssoc-ext` `gssoc` and the level.

**Review by dohinafs — COMMENTED** [review]
The menu cards of the deployed preview don't reflect the color changes you've made in the screenshots. Also do implement the same bg color in the 'apply filter' button, if possible. 
image

**Comment by Kevindua26** [comment]
> The menu cards of the deployed preview don't reflect the color changes you've made in the screenshots. Also do implement the same bg color in the 'apply filter' button, if possible. image

Hey @dohinafs, now check I fixed the card backgorund color problem as well as I applied same on the 'apply filter' button.

**Comment by Kevindua26** [comment]
@dohinafs bro please assign me the `labels` for the level of the issue and other on mu issue #147 also on this pull request 😅

**Comment by Kevindua26** [comment]
Hey @dohinafs i guess you should close the issue now as you merged the pr.

**Pull request merged**
