### PR TITLE
Added Track Order option and Edit Order Option

### PR DESCRIPTION
**Pull request by prvn-kumar01**
I've Added track order and edit options. it can be accessed from the My Order button from the nav bar
Screenshot 2024-10-02 155551

### CODE REVIEW

**Comment by prvn-kumar01** [comment]
why are you reassigned me??
I already done my work

**Comment by dohinafs** [comment]
I just added labels to this PR.

**Comment by prvn-kumar01** [comment]
@dohinafs 
Upgrade it to level 2 .
and I do not get my points for solving this issue .

**Comment by prvn-kumar01** [comment]
Hey @dohinafs  say something I did not get my points yet

**Comment by dohinafs** [comment]
I have added the necessary labels. Point management is not within my scope, kindly contact the required personnel if you're facing issues.

**Comment by prvn-kumar01** [comment]
So what can I do now for point.
Whom should I mail to?

**Pull request merged**
