### PR TITLE
Update X-icon and Improve Readability

### PR DESCRIPTION
**Pull request by poorvikaa08**
@dohinafs 
This pull request updates the Twitter icon to the new X logo and improves code readability through consistent indentation. 

Changes made:
- Replaced the Twitter icon with the new X icon.
- Improved indentation in HTML for better readability.

Please review and let me know if there are any changes needed. Thank You

### CODE REVIEW

**Comment by Altair-05** [comment]
@poorvikaa08  Kindly include a screenshot of the webpage before and after the changes you made

**Comment by poorvikaa08** [comment]
@Altair-05 
Sure, here are the changes I made

Before:
image

After:
image

@Altair-05 @dohinafs 
Please review and let me know if there are any changes needed. 
Thank You

**Comment by Altair-05** [comment]
please check your html and css files ..it has some conflict

**Comment by poorvikaa08** [comment]
@Altair-05 I fetched all the latest updates done so far. I reviewed the html file and updated it successfully. 
Can you verify if the merge conflicts have been resolved?

Or should I create another pull request? 
Please guide, Thank you.

**Review by Altair-05 — APPROVED** [review]

**Comment by Altair-05** [comment]
@poorvikaa08, everything is fine now

**Comment by poorvikaa08** [comment]
@Altair-05 
This contribution isn't counted in gssoc.

**Comment by poorvikaa08** [comment]
Can you reopen this PR and merge it and label it as "gssoc-ext" and the level to make sure that my contribution is counted

**Pull request merged**
