### PR TITLE
Add mini cahtbot to the website

### PR DESCRIPTION
**Pull request by rutikakengal**
#134 issue fixed add  mini cahtbot 
Add gssoc-ext,hactoberfast-accepted and level 3 to this pr 
@dohinafs 

Screenrecording

https://github.com/user-attachments/assets/96f91cb4-bb58-4157-a0ab-1b8cc6106ad2

### CODE REVIEW

**Comment by dohinafs** [comment]
This is how the deployed preview looks like: 
image

**Comment by rutikakengal** [comment]
I solve the problem and resolve conflicts @dohinafs 
Screenrecording

https://github.com/user-attachments/assets/cfd8c9fd-228e-43a0-9654-45bcad9aad84

**Comment by Altair-05** [comment]
@rutikakengal It seems the CSS of other pages has changed compared to the previous update. please check the menu section?

**Comment by adarshsingh0103** [comment]
@rutikakengal  Can you please! assign me to work on this issue.

**Pull request merged**
