### PR TITLE
Modified Button Design and completely changed the all buttons designs.

### PR DESCRIPTION
**Pull request by coderrrx-Brijesh**
I have redesign the websites button theme and made them more responsive and modern.
Also Added Animated-button Class to which all other button inherit and maintain the over all theme of the website and buttons.

### CODE REVIEW

**Comment by dohinafs** [comment]
https://deploy-preview-103--arcticdelights.netlify.app/ shows issues.

**Comment by coderrrx-Brijesh** [comment]
Please merge this pull request before merging someone's else request otherwise more issues can occur cause code will change again and again i need to fix the issue.

**Comment by coderrrx-Brijesh** [comment]
Uploading Update and changes .mp4…
Please note I have attached the changes made here, First I ahve shown how website look after changes made by me and then before changes made

**Comment by coderrrx-Brijesh** [comment]
Please merge this branch, I have solved all the issues

**Comment by coderrrx-Brijesh** [comment]
Please Note there is a bug in your website, same type of ice cream cards are inserted in your original website i have changed them too and fix that bug.

**Comment by Altair-05** [comment]
@coderrrx-Brijesh plz resolve conflicts

**Comment by coderrrx-Brijesh** [comment]
why you are continuously merging other's pull request, that keep raising conflicts, I am solving conflicts one by one and you are  merging other's pull request which again make conflicts. Accept my merges this time before merging any one's else pull request, this is last time  I am solving this conflicts. You have already wasted my lot's of time by merging other's bad quality code in your main.

**Comment by coderrrx-Brijesh** [comment]
do you even see what you accept to merge, i have given you good quality of code and button style but you merged any code without seeing the quality. just watch the video once that i have uploaded for your refrence that what changes i had made.

**Pull request closed without merging**
