### PR TITLE
modified checkout page

### PR DESCRIPTION
**Pull request by bhavanireddy57**
pull request:
issue no#53 closes
Screenshot 2024-10-11 120738
Previously the checkout page was static regardless of no.of items added in cart.so i modifies it to dyanamic feature

### CODE REVIEW

**Comment by bhavanireddy57** [comment]
https://github.com/user-attachments/assets/8fd4a9c0-e6ee-415d-8610-2da8dfe6da62

Also I have added  go back button redirecting to home page.implemented this with existing style of website

**Comment by bhavanireddy57** [comment]
can you please review it and let me know

**Comment by bhavanireddy57** [comment]
Can you please review it and let me know about it

**Review by dohinafs — COMMENTED** [review]
Could you make the text more readable in light mode? 
image

**Comment by bhavanireddy57** [comment]
I have just requested for modifying checkout page with its functionality .so i have created a dynamic checkout also added a goback button redirecting to home page.so can you please merge my pull request up to this.please let me know this

**Comment by dohinafs** [comment]
Okay, resolve the conflicts.

**Comment by bhavanireddy57** [comment]
can you review it and let me know

**Pull request merged**
