### PR TITLE
Fix: Added animations to 'Get yours now' button

### LINKED ISSUE #42: Button Animation
I would like to add a better effect for the 'Get Yours Now' button. Please assign the issue
image

### PR DESCRIPTION
**Pull request by Shreya-0510**
Fix: Added animations to 'Get yours now' button.
Fixes #42

### CODE REVIEW

**Comment by Altair-05** [comment]
@Shreya-0510  Kindly include a screenshot of the webpage before and after the changes you made.and also check the conflict once by

**Comment by Shreya-0510** [comment]
Before:

https://github.com/user-attachments/assets/a0b5ab87-19bf-4119-a438-02155ab08f82

After:

https://github.com/user-attachments/assets/07b7e175-8089-400d-ac47-fb5635b734da

**Comment by Altair-05** [comment]
@Shreya-0510  did u  fetch the latest changes?

**Comment by Shreya-0510** [comment]
> @Shreya-0510 did u fetch the latest changes?

No actually i had sent this pull request an hour ago. Do i have to fork the repository with latest changes and do it again?

**Comment by Altair-05** [comment]
@Shreya-0510 Instead of forking again , please pull the latest changes from the main repository into your fork

**Pull request closed without merging**
