### PR TITLE
added filter options

### PR DESCRIPTION
**Pull request by Pavan8421**
## Now : 
Screenshot 2024-10-04 183236

### CODE REVIEW

**Comment by Pavan8421** [comment]
Please check this pull request @Altair-05

**Comment by Altair-05** [comment]
@Pavan8421  please resolve the conflicts.

**Comment by Pavan8421** [comment]
please assign the labels

**Comment by Pavan8421** [comment]
please assign the labels for this pull request also @dohinafs

**Comment by Pavan8421** [comment]
why these pull requests are not reflecting to leader board of gssoc-ext 2024?

**Pull request merged**
