### PR TITLE
ADDED FEW INPUT SECTIONS IN SIGN-UP POP-UP and CHANGED the APPERANCE of FILTER SECTION also changed the Hover Effect

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
Added NAME and PASSWORD fields in Sign-UP POP-UP !
(BEFORE)
Screenshot 2024-10-10 222735

(AFTER)
Screenshot 2024-10-10 224825

CHANGED the APPERANCE of FILTER SECTION also changed the Hover Effect
(BEFORE)
Screenshot 2024-10-10 232450

(AFTER)
Screenshot 2024-10-11 001856

NEW CHANGED HOVER EFFECTS :
Screenshot 2024-10-11 001918
AND
Screenshot 2024-10-11 001937

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@dohinafs Please consider My Pull Request and assign LABELS to it

**Review by PatelHarsh2006 — COMMENTED** [review]
Ready to merge

**Comment by PatelHarsh2006** [comment]
@dohinafs Please consider My Pull Request and PLEASE assign LEVEL 2 or LEVEL 3 label to it !!!

**Review by dohinafs — APPROVED** [review]

**Comment by PatelHarsh2006** [comment]
@dohinafs Sir, can U please assign it LEVEL-2 !!!

**Pull request merged**
