### PR TITLE
CHANGED the CURSOR Animation to INDIAN Tricolor Theme

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
CHANGED the CURSOR Animation to INDIAN Tricolor Theme

(BEFORE):
https://github.com/user-attachments/assets/b6420a2b-2af7-4f12-859b-600df4882163

(AFTER):
https://github.com/user-attachments/assets/1d16fd55-e451-4edc-8bc8-e3bf7a0c0e0f

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@dohinafs Please, Review My Changes and Merge it by Assigning Labels to it !

**Comment by dohinafs** [comment]
Kindly resolve conflicts.

**Comment by PatelHarsh2006** [comment]
> Kindly resolve conflicts.

@dohinafs Conflict has been Resolved

**Comment by PatelHarsh2006** [comment]
@dohinafs Sir, Conflicts are resolved, So Please MERGE my Pull Request !

**Comment by PatelHarsh2006** [comment]
@dohinafs Sir, Conflicts are resolved, So Please MERGE my Pull Request !

**Pull request closed without merging**
