### PR TITLE
google-signin-frontend

### PR DESCRIPTION
**Pull request by NK-Works**
I have added the google signin frontend where the frontend sends the access_token to the backend for checking...
Just make sure to add the google cleint id where i have mentioned in the `google_signup.js` and the popout for the signup feature will activate.
Solves: #494

### CODE REVIEW

**Comment by dohinafs** [comment]
Kindly resolve conflicts.

**Comment by NK-Works** [comment]
@dohinafs resolved

**Comment by NK-Works** [comment]
Solves: #494

**Comment by NK-Works** [comment]
@dohinafs please merge the pr its been 2 weeks now

**Comment by NK-Works** [comment]
@dohinafs please make it a level 3 sol at this point with the amount of conflicts that got added it was too much

**Comment by NK-Works** [comment]
@dohinafs can please stop merging for a sec....
i resolved teh conflicts three times just to get that file updated and all my work wasted

**Comment by NK-Works** [comment]
@dohinafs resolved all conflicts

**Comment by NK-Works** [comment]
@dohinafs all conflicts resolved kindly merge...
would really appreacite a level upgrade to level3 due to the sheer amout of conflicts that i had to resolve around 22 after you merged so many today////

**Comment by NK-Works** [comment]
@dohinafs please merge the pr as only a day remains in the GSSOC...
At this its a request please dont let my work go waste 🙏

**Pull request closed without merging**
