### PR TITLE
Our menu section updated!

### PR DESCRIPTION
**Pull request by isnehamondal**
I have changed the appearance of the menu section. I have made some changes in its display which was earlier grid but because of that it had some issues when we change the screen size so i changed it to flex and some other changes as well. I have carefully considered the theme of the website and used those colors and fonts to improve it. I also made some changes in the html page and updated the our menu heading with "Here's, what we have in store for you". This made the whole section look even better and suited it. 
Hope you like this work. If you want to make any more changes, please tell me I would love to do it and if you like this contribution, please do merge it.

### CODE REVIEW

**Comment by Altair-05** [comment]
@isnehamondal  Kindly include a screenshot of the webpage before and after the changes you made

**Comment by isnehamondal** [comment]
Here are the screenshots. There are some hover effects too.
updated menu 1
updated menu 2
updated menu 3
If you need to make any other changes, please tell me, I will do it.

**Comment by Altair-05** [comment]
@isnehamondal kindly  fetch the latest changes from the main branch to stay updated and minimize merge conflicts

**Comment by isnehamondal** [comment]
Okay, I will update you with the final one.

**Pull request closed without merging**
