### PR TITLE
Redesigned The headings(issue #201)

### PR DESCRIPTION
**Pull request by Gaurav075**
I have successfully redesigned the headings i.e, About Us, Our Blogs & and here's, what we have in store for you! . Now these readings look more clear and attractive both in light and dark mode.

### CODE REVIEW

**Comment by dohinafs** [comment]
@Gaurav075  Your corrections still make it difficult for the headings to be visible.
Light mode:
image
Dark mode:
image

**Comment by Gaurav075** [comment]
@Altair-05 login,signup button visibility is corrected successfully. @dohinafs

**Comment by Gaurav075** [comment]
@dohinafs the pics of About Us you have displayed here is another error when you refresh color changes . I have set black for light theme and white for dark theme.
Screenshot (330)
Screenshot (331)
Screenshot (332)
Screenshot (333)
Screenshot (334)
Screenshot (335)

**Comment by Altair-05** [comment]
@Gaurav075 

The login/signup section is visible, but other sections are not... Please check 
image

**Pull request closed without merging**
