### PR TITLE
✨Backend functionality added for the forms✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
the issue #265 has been solved

https://github.com/user-attachments/assets/02efda9c-d016-4b09-b77d-36baeca7025b

@dohinafs can you please review this and add the levels.
thank you!

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Altair-05 can you please review this , i have chatbot to PR too.

**Comment by T-Rahul-prabhu-38** [comment]
@dohinafs  @Altair-05 can you please review this , i have chatbot to PR too.

**Comment by T-Rahul-prabhu-38** [comment]
@Altair-05 this PR

**Comment by T-Rahul-prabhu-38** [comment]
@Altair-05 review this PR,i have the chatbot one remaining.

**Review by dohinafs — APPROVED** [review]

**Review by dohinafs — COMMENTED** [review]
Will the review not be stored but be overwritten? 

https://github.com/user-attachments/assets/2ef3a0f5-9d4e-47d0-a8e0-46f9830c4278

**Comment by T-Rahul-prabhu-38** [comment]
good point , i can make it store , ill add that feature immediately. initially i thought only 1 review will be sent , ill fix it asap.

**Pull request closed without merging**
