### PR TITLE
Implement animated circles and improve blog layout

### LINKED ISSUE #438: Enhance Blog Page with Animated Circles and Improved Layout for Better User Experience
**Issue:** The original blog page lacked visual engagement and interactivity, resulting in a static user experience. The absence of dynamic elements made it less appealing, potentially causing visitors to lose interest quickly. The blog details section also had a basic layout that did not effectively showcase the content, leading to a missed opportunity for storytelling and user connection.

### PR DESCRIPTION
**Pull request by akhulisumit**
fixes #438 
- **Changes Made:**
  - **Animated Circles:** Introduced animated circles that follow the mouse cursor, creating an interactive experience. This feature adds a layer of fun and encourages user exploration of the page.
  - **Blog Layout Enhancements:** Reworked the layout of the blog details section to improve readability and aesthetics. Each blog post now features:
    - An eye-catching title in a vibrant color that aligns with the theme.
    - High-quality images relevant to the content, enhancing visual storytelling.
    - Well-structured paragraphs that provide insightful descriptions, inviting users to read more.
  - **Styling Improvements:** Updated CSS to create a cohesive design that includes:
    - A warm background color that evokes the theme of ice cream.
    - Responsive design adjustments to ensure that the blog looks great on both desktop and mobile devices.
  - **Overall User Experience:** The combination of animated elements and a visually appealing layout aims to engage users more effectively, encouraging them to interact with the content and explore further. 

image

### CODE REVIEW

**Comment by dohinafs** [comment]
Kindly provide screenshots of your improvements

**Comment by akhulisumit** [comment]
before update:
image

After update:
image

**Comment by akhulisumit** [comment]
Before update:
image
image
image


After Update
image
image

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly remove the changes on the footer as this issue has already been raised and assigned before you did so. 
After you do, I will merge the PR on the changes in the blogs.

**Comment by akhulisumit** [comment]
changes made as you requested

**Comment by akhulisumit** [comment]
> Kindly remove the changes on the footer as this issue has already been raised and assigned before you did so. After you do, I will merge the PR on the changes in the blogs.

Commit made as you requested

**Review by dohinafs — APPROVED** [review]

**Comment by akhulisumit** [comment]
I’ve recently contributed to the repository . Could you please add the gssoc-ext label to my contributions so that they are recognized under the program?

Thank you for your help!

**Comment by dohinafs** [comment]
Yes, kindly resolve the conflicts and I'll merge the PR and also add the necessary labels.

**Comment by akhulisumit** [comment]
can you please provide the Gssoc-ext tag

**Pull request closed without merging**
