### PR TITLE
Create  menu page (new design)

### PR DESCRIPTION
**Pull request by AyushiTaralkar**
new menu page design as per ne theme.
Issue #87

### CODE REVIEW

**Comment by Altair-05** [comment]
@AyushiTaralkar, are you making changes according to the new Figma design?

**Comment by AyushiTaralkar** [comment]
> @AyushiTaralkar, are you making changes according to the new Figma design?yes

**Comment by Altair-05** [comment]
image
image
Please change the CSS of the menu page in light mode, and update the sign-up/login buttons in dark mode, as they are not visible.

**Comment by dohinafs** [comment]
> @AyushiTaralkar Please change the CSS of the menu page in light mode, and update the sign-up/login buttons in dark mode, as they are not visible.

These issues have already been put forward and assigned to other contributors.

**Comment by AyushiTaralkar** [comment]
act

> 

Thank you for clearing I got confused.

**Comment by Altair-05** [comment]
> > @AyushiTaralkar Please change the CSS of the menu page in light mode, and update the sign-up/login buttons in dark mode, as they are not visible.
> 
> These issues have already been put forward and assigned to other contributors.


@dohinafs  okay!

**Comment by Altair-05** [comment]
@AyushiTaralkar, what new changes have you made? plz attach ss

**Comment by AyushiTaralkar** [comment]
> @AyushiTaralkar, what new changes have you made? plz attach ss

sure
Screenshot 2024-10-04 170136
Screenshot 2024-10-04 170123
Screenshot 2024-10-04 170108
Screenshot 2024-10-04 120235

**Comment by AyushiTaralkar** [comment]
I have made the design other collaborators are also working on it as they also have been assigned the same task under issue #163

**Pull request merged**
