### PR TITLE
Enhanced Contact page 

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
# Improved Contact Page Layout by applying Proper CSS
-> Applied proper styling for each element 
-> It will make page more User interactive 

https://github.com/user-attachments/assets/17a8ad8d-a935-4d17-995d-79f5ceec4632

Please merge the pull request and give a Level3 Label .

### CODE REVIEW

**Comment by AnujShrivastava01** [comment]
@dohinafs
I have fixed the Contact page 
Please merge the pull request and give a level3 label.

**Review by dohinafs — CHANGES_REQUESTED** [review]
This is how it appears in the deployment preview:
image

**Comment by AnujShrivastava01** [comment]
image
I have fixed it !
Now Please Merge the pull request and give a level3 label in PR .

**Review by dohinafs — COMMENTED** [review]
This is how the deployed preview looks right now:
image

**Pull request closed without merging**
