### PR TITLE
Create SignUp.html

### PR DESCRIPTION
**Pull request by Aryam2121**
Real-time Validation:

Error messages are displayed immediately when the user inputs incorrect data, improving user experience. Password Strength Indicator:

Users get instant feedback on their password strength, encouraging stronger passwords. Confirmation Email Simulation:

Alerts the user upon successful registration, simulating an email sent for confirmation. Responsive Design:

Uses flexbox for centering and a responsive design approach to make it look good on mobile devices. Improved User Experience:

Button styles enhance the overall appearance and user interaction. Loading animation during form submission gives feedback that the application is processing their request.solve issue #215

### CODE REVIEW

**Comment by dohinafs** [comment]
Kindly link the changes to index.html

**Comment by Aryam2121** [comment]
Ok

**Comment by Aryam2121** [comment]
Merge this first please

**Comment by Aryam2121** [comment]
merge my code as soon as possible

**Comment by dohinafs** [comment]
@Aryam2121 Could you link this PR to the issue that was assigned to you?

**Comment by Aryam2121** [comment]
I already link #215 issue

**Comment by dohinafs** [comment]
> I already link #215 issue

Yes, but #215 has not been assigned to you. Where you assigned to any issue relevant to this PR?

**Comment by Aryam2121** [comment]
but i solve so you assign to me and merge this

**Pull request closed without merging**
