### PR TITLE
Created a resposive toggle button for small pages

### PR DESCRIPTION
**Pull request by sayanp607**
https://github.com/user-attachments/assets/03adfe61-734e-43fe-b444-b922ef7f2284

the toggle button will appear for small pages, the options will navigate to proper pages, the dropdown window disappears after clicking on a option or outside it,  the text are having hover effects also. Hope you like it.

### CODE REVIEW

**Review by Altair-05 — CHANGES_REQUESTED** [review]
Here's a more concise version:

@sayanp607,

ur design doesn't align with the existing UI. Please adjust it to better match the exisiting look

**Comment by sayanp607** [comment]
@Altair-05 sure , but can you please tell me which portion need to improve? Like the background color of the drop down item , that's what caused the text is appearing on the existing UI.

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly make the following changes:
1. The background of the dropdown is transparent, give it a bg color that matches the site in light and dark mode. 
2. The color of the text doesn't match with the site's theme. Look at the colors in the site and pick one that matches. 
3. The toggle button is too close to the heading Arctic Delights, include appropriate spacing there. 
4. The orders button is of a different size, fix this. 
image

**Comment by sayanp607** [comment]
I have changed all the requested issues , please check it @Altair-05 , @dohinafs , and please make sure if I have to change anything more, always ready for it.

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly fix the following issues:
1. Upon hover, the button text disappears into the side. 
2. Either the size of the bg can be reduced or the text can be center aligned to make this design look better. 
image

**Comment by sayanp607** [comment]
Screenshot 2024-10-13 190759
Is it ok now? or should I bring more changes? Please let me know @dohinafs

**Comment by dohinafs** [comment]
Have you committed the changes? I'm unable to see them...

**Comment by sayanp607** [comment]
> Have you committed the changes? I'm unable to see them...

Yes, previously I just shared the screenshot , now I made the commit. Please check it.

**Review by dohinafs — COMMENTED** [review]
It looks good but could you make contact us and my orders in one line instead of two? I couldn't see this difference in your screenshots, so kindly fix this and I'll merge your PR.
image

**Comment by sayanp607** [comment]
> It looks good but could you make contact us and my orders in one line instead of two? I couldn't see this difference in your screenshots, so kindly fix this and I'll merge your PR. image
1>
Screenshot 2024-10-16 095504
2>
Screenshot 2024-10-16 100724
look which one you prefer if contact us and my orders will come in one line. where decreasing the font-size and the padding makes it looks so nasty. So, I think it should not be decreased. @dohinafs

**Comment by dohinafs** [comment]
I'd like it like this: 
image

**Comment by sayanp607** [comment]
> I'd like it like this: image

yeah, I have done this & made the commit. Please merge my pr now.

**Review by dohinafs — APPROVED** [review]

**Pull request merged**
