### PR TITLE
"Implementing Scroll Animations, Hover Effects, and Transitions Using CSS and JS"

### PR DESCRIPTION
**Pull request by sambedan1**

### CODE REVIEW

**Comment by sambedan1** [comment]
#105 done

**Comment by Altair-05** [comment]
@sambedan1  plz resolve the conflicts

**Comment by sambedan1** [comment]
please check my pr

**Comment by dohinafs** [comment]
This is the view of the deployment preview of your PR:
https://deploy-preview-105--arcticdelights.netlify.app/

**Pull request closed without merging**
