### PR TITLE
Added password strength indicator on signup page

### PR DESCRIPTION
**Pull request by jvkousthub**
image
image
image

solves #467

### CODE REVIEW

**Comment by jvkousthub** [comment]
Solved #467

**Comment by jvkousthub** [comment]
@dohinafs Please review and let me know if any changes required

**Review by dohinafs — CHANGES_REQUESTED** [review]
Despite the fact that the password is not good, we are still able to create an account, kindly fix this. 
image

**Comment by jvkousthub** [comment]
Ok I'll fix it

**Comment by jvkousthub** [comment]
@dohinafs Fixed it

**Pull request closed without merging**
