### PR TITLE
Added 'Shop Items' page for displaying details of selected ice cream. 

### PR DESCRIPTION
**Pull request by ThunderShadows**
I have made a page called "Shop Items" dedicated to describe the details of the ice cream such as SKU, Availability, flavour and overall reviews given my the customer. And an add a new item to the cart or increase the quantity of the items is also added to it. Check the overall picture here--

Screenshot 2024-10-07 221017

### CODE REVIEW

**Comment by Altair-05** [comment]
@ThunderShadows There is no option to revert from this section. Please check

**Comment by ThunderShadows** [comment]
> @ThunderShadows There is no option to revert from this section. Please check

I shall include a return to menu page for each item selected. Sorry for the inconvenience caused.

**Comment by dohinafs** [comment]
@ThunderShadows The add to cart button in the new page doesn't seem to work. And it would be better if you added a read more button or link which will take them to this section.

**Comment by ThunderShadows** [comment]
> @ThunderShadows The add to cart button in the new page doesn't seem to work. And it would be better if you added a read more button or link which will take them to this section.

In the Main menu, shall i add a read more section in each ice cream block so that users will be redirected to respective pages like these which i have created, and then i shall remove the add to cart section in my new html pages. So that it gives the description of the ice cream and details only. Shall i do it?

**Comment by dohinafs** [comment]
> 
> In the Main menu, shall i add a read more section in each ice cream block so that users will be redirected to respective pages like these which i have created, and then i shall remove the add to cart section in my new html pages. So that it gives the description of the ice cream and details only. Shall i do it?

Yes, the above sounds good. If possible, it would be better for it to be a pop up displaying the details that can be closed after being read.

**Comment by adarshsingh0103** [comment]
@ThunderShadows  Can you please! assign me to work on this issue.

**Pull request merged**
