### PR TITLE
Improve page load

### PR DESCRIPTION
**Pull request by shreyad2806**
#33 
Added files and photo compression in js. Please give level2 as I have made changes in js
Changes made
1.use the loading attribute in HTML
2. For image compression,  used TinyPNG's API in js
3. For minifying CSS, JavaScript, and HTML files, used Gzip and Brotli in js
4. Optimize Server and Network in js

### CODE REVIEW

**Comment by shreyad2806** [comment]
#34 
Added animations

**Comment by shreyad2806** [comment]
#33  #115 
updated

**Comment by shreyad2806** [comment]
Is both issue ok or do I have to do any changes?

**Review by shreyad2806 — COMMENTED** [review]
Added animations

**Comment by Altair-05** [comment]
image

@shreyad2806 The "Get Yours" button's CSS doesn't look good (#34), and the font color on the homepage is also not very visible

**Comment by shreyad2806** [comment]
this is not done by me. I have added animations in css and page loading
improvement in js.

**Pull request closed without merging**
