### PR TITLE
Implemented a toast-style notification system message removing windows Alert 

### PR DESCRIPTION
**Pull request by ananyag309**
solved #530 

working demo:

https://github.com/user-attachments/assets/788a27ec-ccca-46f5-9dc6-fb50aa73d48d

### CODE REVIEW

**Comment by ananyag309** [comment]
@dohinafs please review and merge it

**Comment by dohinafs** [comment]
Kindly resolve conflicts.

**Comment by ananyag309** [comment]
@dohinafs resolved

**Comment by ananyag309** [comment]
@dohinafs please merge it

**Comment by ananyag309** [comment]
@dohinafs please merge it as i already resolved the conflicts

**Comment by ananyag309** [comment]
@mastansayyad please have a check on this too its been almost 2 weeks no one is merging it

**Pull request merged**
