### PR TITLE
added ui and features

### PR DESCRIPTION
**Pull request by aditya07389**
### hey @dohinafs i have added the changes i proposed 
Issue number : #268 

## 1) Added Scrollreveal/rollover animation for the page :

i added javascript functions to handle scroll reveal animations , which is a better way to handle it rather than using css data ose animations

#### video demo  for scroll reveal and number of items in the cart fucntionality 

https://github.com/user-attachments/assets/3f488c2b-5ca8-438a-8619-c4ab88d70a4a

## 3) Improving the design of back to top button 

WhatsApp Image 2024-10-09 at 12 55 34_67b591ea

I hope you are satisfied with the work !!

Kindly add the labels : gssoc extd , hacktoberfest and level 3

### CODE REVIEW

**Comment by aditya07389** [comment]
@dohinafs all conflicts have been resolved , you can merge now :-)

**Comment by aditya07389** [comment]
@dohinafs can you please merge it

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly correct the following issues:
1. This is how the menu is appearing in the preview:
image
image
2. The about me section was previously center aligned, now it has become left aligned which doesn't look good. 
image

**Comment by aditya07389** [comment]
@dohinafs I have no idea why those things happened , It was looking fine on my local system , ill look into it right away !!

**Comment by aditya07389** [comment]
hey @dohinafs ill create a new pull request soon , u can close this one , ill create the new one by today, thannkyou

**Pull request closed without merging**
