### PR TITLE
chatbot added

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
i have given my version of chatbot as the last one wasnt working , hope u like it!

https://github.com/user-attachments/assets/b0103849-6cd1-40be-a0ee-eb072ff419ae

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
issue #341 has been solved.
@dohinafs @Altair-05  can you review this please.
Thank you!

**Review by dohinafs — COMMENTED** [review]
Could you change the name of this from netlify.app to ArcticDelights or to some other suitable text? 
image

**Comment by T-Rahul-prabhu-38** [comment]
i can do that
what name do u prefer.

**Comment by dohinafs** [comment]
Just change it to ArcticDelights

**Comment by T-Rahul-prabhu-38** [comment]
done

**Comment by T-Rahul-prabhu-38** [comment]
it should reflect immediately.

**Review by dohinafs — APPROVED** [review]

**Pull request merged**
