### PR TITLE
[Feature enhancement] : ✨ Dark mode toggle added ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
the dark mode toggle switch is added, please review the PR @dohinafs 
Thank you!.

https://github.com/user-attachments/assets/1a9cad7d-ebe7-4612-ad17-c9afca3348eb

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
can you please assign the level as well, Thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@dohinafs  bro im assuming there is a problem with the tag you have used, its not level2 and its level 2. can you fix it as it hasnt reflected on leaderboard for me . Your help would really mean a lot

**Comment by T-Rahul-prabhu-38** [comment]
@sanjay-kv sir the level 2 tag isnt the correct tag and because of this, this PR isnt reflecting on the leaderboard , can you please help me fix this sir.

**Comment by dohinafs** [comment]
This is the message from the discord group: 

The correct labels are gssoc-ext, level1, level2, and level3.
NOTE: Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

**Comment by T-Rahul-prabhu-38** [comment]
yea can u try the one with space
because 4 level 2 projects are reflecting with space between them

**Comment by T-Rahul-prabhu-38** [comment]
one this PR isnt displayed

**Comment by T-Rahul-prabhu-38** [comment]
Screenshot 2024-10-06 at 9 22 00 AM
 
what can i do to fix this issue.

**Comment by sanjay-kv** [comment]
@T-Rahul-prabhu-38 I will talk with the team regarding this.

**Comment by sanjay-kv** [comment]
@T-Rahul-prabhu-38 i couldnt find this repo under listed projects. from where you got this repo

**Comment by sanjay-kv** [comment]
WhatsApp Image 2024-10-06 at 15 59 08_07b2f2c6

admin have you changed the repo URL or something. ?

**Comment by T-Rahul-prabhu-38** [comment]
> @T-Rahul-prabhu-38 I will talk with the team regarding this.

thank you sir

**Comment by dohinafs** [comment]
@sanjay-kv Yes, it was previously a static link but I have deployed the site with netlify to reflect the changes as they're updated to main. It was changed to https://arcticdelights.netlify.app/

**Comment by T-Rahul-prabhu-38** [comment]
@sanjay-kv  sir can this be fixed , as its still not reflecting on the leaderboard.

**Comment by sanjay-kv** [comment]
its already fixed it should be available on leaderboard @T-Rahul-prabhu-38

**Comment by T-Rahul-prabhu-38** [comment]
@sanjay-kv sir its still not displayed on the leaderboard.

**Comment by sanjay-kv** [comment]
they have changed the url of the project, it will take a day to reflect the change

**Comment by T-Rahul-prabhu-38** [comment]
sure sir

**Pull request merged**
