### PR TITLE
Added contributors in about us section

### PR DESCRIPTION
**Pull request by ishakatiyar06**
I have added a list for contributors in the about us section.

### CODE REVIEW

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly fix the following:
1. Change the titular text and following subtext according to what I've slashed out. 
image
image
2. Text not visible in dark mode. 
image
3. The whole site turns black in dark mode but this section remains with a light bg, kindly fix this. 
image
4. It would be better if you added more padding to the sides and shrunk the size of the contributor's profile and usernames and make it into 6 contributors in one row 
image

**Comment by ishakatiyar06** [comment]
Sure. I'll do it.

**Comment by ishakatiyar06** [comment]
I have made the changes. Please look into it.

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly fix the below:
1. Format the title to match the titles in the rest of the site
image
image
2. Kindly fix point 4 in the previous review.

**Comment by ishakatiyar06** [comment]
Screenshot 2024-10-14 165921
I have the changed the title to match the title of the website.
Screenshot 2024-10-14 165908
Size of the profiles is shrinked.

**Comment by ishakatiyar06** [comment]
Hey there, @dohinafs. Is there any problem or correction in my PR, you haven't merged it yet?. If there is something, I am ready to do it.

**Pull request merged**
