### PR TITLE
This PR is related to issue #497.Privacy.html created.

### PR DESCRIPTION
**Pull request by Priyank00007**
image
I have also added the link on navbar.

### CODE REVIEW

**Review by Altair-05 — APPROVED** [review]

**Comment by Priyank00007** [comment]
Is the PR closed?

**Comment by Priyank00007** [comment]
pls add the label required @Altair-05

**Comment by Priyank00007** [comment]
@dohinafs pls merge this PR

**Comment by Priyank00007** [comment]
@Altair-05 close this pr pls

**Pull request merged**
