### PR TITLE
add Contact us page to website

### PR DESCRIPTION
**Pull request by rutikakengal**
#79 issue fixed @dohinafs 

screenshots of the contact us page 

Screenshot 2024-10-03 111438

### CODE REVIEW

**Comment by rutikakengal** [comment]
please add gssoc ext, hactoberfest accepted, level labels @dohinafs

**Comment by rutikakengal** [comment]
Why this score is not showing me in my leaderboard you are merging or not @dohinafs

**Comment by dohinafs** [comment]
I have added the correct labels so it should show up for you.

**Comment by rutikakengal** [comment]
but this pr is not showing on my leaderboard @dohinafs

**Comment by rutikakengal** [comment]
You merging the pr but my in leaderboard is not showing . are you adding labels or not in pr @dohinaf

**Comment by dohinafs** [comment]
> You merging the pr but my in leaderboard is not showing . are you adding labels or not in pr @dohinaf

Kindly check the labels mentioned before commenting.

**Pull request merged**
