### PR TITLE
fixed the logo and navbar alignment

### PR DESCRIPTION
**Pull request by sakshikedari**
Issue: Fixed the inconsistent alignment between the logo and the navbar across different screen sizes.

Changes Made:

Adjusted the spacing between the logo on the left and navbar items on the right.
Ensured responsive design consistency across all screen sizes.
Before Changes: 
Screenshot 2024-10-11 181916
After Changes: 
Screenshot 2024-10-11 181843

### CODE REVIEW

**Comment by Altair-05** [comment]
@sakshikedari  plz resolve the conflicts

**Comment by sakshikedari** [comment]
resolved the conflict

**Comment by sakshikedari** [comment]
@Altair-05 I have resolved the conflicts in my pull request [#472 ]. Could you kindly review it at your earliest convenience?

**Review by dohinafs — APPROVED** [review]

**Comment by sakshikedari** [comment]
Please give me some level

**Pull request merged**
