### PR TITLE
code readability of popup increased

### LINKED ISSUE #418: BUG: In Dark mode, Signup popup is not visible
The Text is not visible properly in dark mode

Screenshot:

image

Assign me, i will solve it

### PR DESCRIPTION
**Pull request by SiddarthaKarri**
Issue: Fixed #418 

Description:
Fixed the visibility of popup

Screenshot:
Before:
image

After:
image

### CODE REVIEW

**Review by Altair-05 — COMMENTED** [review]
image


@SiddarthaKarri  It is clearly visible

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly fix the following issue and I will merge your PR after that.
We are unable to see the below contents clearly in both light and dark modes. 
image
image

**Comment by dohinafs** [comment]
Kindly implement the necessary changes.

**Comment by SiddarthaKarri** [comment]
@dohinafs i fixed it
image

**Comment by dohinafs** [comment]
Kindly resolve conflicts and I'll merge your PR as soon as possible.

**Pull request closed without merging**
