### PR TITLE
✨created login page and signup page with backend functionality✨(solved issue#342)

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
its working perfectly with backend functionality where only on signup u can login.
(solved issue#342)
@dohinafs @Altair-05 can you please review this .
Thank you!

https://github.com/user-attachments/assets/f7071570-3511-49ff-bcf3-a0f24d40e548

### CODE REVIEW

**Review by dohinafs — CHANGES_REQUESTED** [review]
Kindly correct the following:
1. When we click the sign up button, it shows a page where the home and login button are lower than the card.
https://github.com/user-attachments/assets/93b155c7-6b0c-48a1-a219-373976b7eedc

3. Similar to the review PR, is it possible for data to be stored rather than overwritten?
4. It takes multiple clicks to go to home page or login page when in siqn up page and the similar is true for login page too. 
5. The button color doesn't match the site's theme
Your preview version:
image
Before:
image

**Comment by T-Rahul-prabhu-38** [comment]
got it , ill fix them all and create a new PR in few mins.

**Comment by T-Rahul-prabhu-38** [comment]
@dohinafs i needed a small help , can you merge this quickly and ill create a new PR cause its asking me to sync my code and ill have hard time recreating 7 pages.

I will create a new issue and dont tag any labels to it.

**Comment by T-Rahul-prabhu-38** [comment]
@dohinafs @Altair-05 i needed a small help , can you merge this quickly and ill create a new PR cause its asking me to sync my code and ill have hard time recreating 7 pages.

I will create a new PR and dont tag any labels to it.

**Comment by T-Rahul-prabhu-38** [comment]
ill do the new pr in sometime now.

**Comment by T-Rahul-prabhu-38** [comment]
i should work on the merge branch right?

**Comment by T-Rahul-prabhu-38** [comment]
@dohinafs i have made a new PR as requested above can you please assign the levels here.
thank you!

**Pull request merged**
