### PR TITLE
added checkout page

### PR DESCRIPTION
**Pull request by bhavanireddy57**
pull request:
issue no:#53 
I have added a separate checkout page to this after clicking checkout button in the cart. can you review it and let me know if any changes required.
Screenshot 2024-10-07 173531

### CODE REVIEW

**Comment by bhavanireddy57** [comment]
Can you please review it and let me know .

**Comment by bhavanireddy57** [comment]
can you please review it and update me with level label

**Comment by bhavanireddy57** [comment]
can you review it and also add the level labels to it

**Comment by Altair-05** [comment]
image

@bhavanireddy57  Please check, as it redirects to the page above when clicking on the checkout button. Also, add a button to go back to the previous page

**Comment by bhavanireddy57** [comment]
Screenshot 2024-10-09 220121

Uploading Screen Recording 2024-10-09 220216.mp4…

**Comment by bhavanireddy57** [comment]
https://github.com/user-attachments/assets/38cbc614-caf9-4f8b-8b28-bda8702d4145

Screenshot 2024-10-09 220121

**Comment by bhavanireddy57** [comment]
Can you once review it and let me know please

**Comment by bhavanireddy57** [comment]
I have modified checkout page with when u click checkout it redirects to confirmation page and from there u can return to home page and also in checkout page i have added go back button to return to homepage

**Comment by bhavanireddy57** [comment]
So please review it and let me know

**Comment by Altair-05** [comment]
> can u please elaborate in detail so that i will change it accordingly

image
image

A better design is already in place; you just need to enhance it further

**Pull request closed without merging**
