### PR TITLE
Using_Trusted_Mail_Services_For_Signup

### PR DESCRIPTION
**Pull request by smog-root**
**Issue_id**: #499 

**Modified signup.html**:

signup.html

**Changes Made:**

**Email Domain Validation:**

Implemented a validation function that checks if the entered email belongs to an allowed domain (Gmail, Outlook, Yahoo).
If the email domain is invalid, an appropriate error message is displayed to the user.

**UI Enhancements:**

Error messages are now shown in real-time, providing immediate feedback to users on their input.

**Trusted mail services:**

gmail.com , outlook.com , yahoo.com , protonmail.com , icloud.com , tutanota.com , hotmail.com

Note:- Add all labels added to issue #499 to this PR. So that GSSoC team can easily recognize the commit!

### CODE REVIEW

**Comment by dohinafs** [comment]
Kindly resolve conflicts.

**Comment by smog-root** [comment]
> Kindly resolve conflicts.

Solved! merge it!

**Comment by smog-root** [comment]
it's been 5days!! @dohinafs merge it!

**Comment by smog-root** [comment]
@dohinafs conflicts are removed!! megre it!!

it's been a week. i create this PR!

**Comment by smog-root** [comment]
@dohinafs hey??

**Comment by MastanSayyad** [comment]
@dohinafs if you're active then kindly merge the open PRs!

**Pull request merged**
